#! /usr/bin/env python

import rospy
from time import sleep

import sl1m_ros
print(sl1m_ros)
import sys
print(sys.path)

print("src/nodes" in sys.path)

from sl1m_ros.sl1m_node import Sl1mNode

def main():
    rospy.init_node('sl1m_node')

    sl1m_node = Sl1mNode()

    while not rospy.is_shutdown():
        sl1m_node.plot_if_results()
        sleep(0.1)


if __name__ == '__main__':
    main()
